# Generated by Django 5.2.5 on 2025-10-09 21:01

from django.db import migrations


def create_leader_role(apps, schema_editor):
    """Создает роль 'Руководитель' если она не существует"""
    Role = apps.get_model('teams', 'Role')
    Role.objects.get_or_create(
        name='Руководитель',
        defaults={'description': 'Руководитель команды с полными правами управления'}
    )


def reverse_create_leader_role(apps, schema_editor):
    """Удаляет роль 'Руководитель' при откате миграции"""
    Role = apps.get_model('teams', 'Role')
    Role.objects.filter(name='Руководитель').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_leader_role, reverse_create_leader_role),
    ]
