# Generated by Django 5.2.5 on 2025-10-09 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_create_leader_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Создана'), ('deactivated', 'Приостановлена'), ('reactivated', 'Возобновлена'), ('disbanded', 'Распущена')], max_length=20)),
                ('old_status', models.CharField(blank=True, choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('disbanded', 'Распущена')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('disbanded', 'Распущена')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Причина изменения статуса')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('disbanded', 'Распущена')], default='active', help_text='Текущий статус команды', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли участник в команде'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='teams_team_status_d66a03_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['creator', 'status'], name='teams_team_creator_acf07f_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'is_active'], name='teams_teamm_team_id_e0780a_idx'),
        ),
        migrations.AddField(
            model_name='teamstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamstatushistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='teamstatushistory',
            index=models.Index(fields=['team', '-timestamp'], name='teams_teams_team_id_f6e4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='teamstatushistory',
            index=models.Index(fields=['changed_by', '-timestamp'], name='teams_teams_changed_f03175_idx'),
        ),
    ]
