# Generated by Django 5.2.5 on 2025-10-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_populate_team_lifecycle_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
