# Generated by Django 5.2.5 on 2025-10-12 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0006_alter_teammembership_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'permissions': [('can_manage_team', 'Может управлять командой'), ('can_invite_members', 'Может приглашать участников'), ('can_remove_members', 'Может удалять участников'), ('can_assign_roles', 'Может назначать роли'), ('can_change_team_status', 'Может изменять статус команды'), ('can_create_project', 'Может создавать проекты'), ('can_manage_project', 'Может управлять проектами'), ('can_delete_project', 'Может удалять проекты'), ('can_assign_chapters', 'Может назначать главы'), ('can_edit_content', 'Может редактировать контент'), ('can_review_content', 'Может рецензировать контент'), ('can_publish_content', 'Может публиковать контент')], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Является ли роль стандартной (создается автоматически)', verbose_name='Стандартная роль'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Разрешения, назначенные этой роли', related_name='roles', to='auth.permission', verbose_name='Разрешения'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание роли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название роли'),
        ),
    ]
