# Generated by Django 5.2.5 on 2025-10-12 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_create_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли роль для пользователя', verbose_name='Активна')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначена')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_global_roles', to=settings.AUTH_USER_MODEL, verbose_name='Назначена пользователем')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_users', to='teams.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Глобальная роль пользователя',
                'verbose_name_plural': 'Глобальные роли пользователей',
                'indexes': [models.Index(fields=['user', 'is_active'], name='teams_userr_user_id_1c05b5_idx'), models.Index(fields=['role', 'is_active'], name='teams_userr_role_id_6a5544_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
