# Generated by Django 5.2.5 on 2025-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватарка пользователя', null=True, upload_to='avatars/'),
        ),
    ]
