# Generated by Django 5.2.5 on 2025-10-11 22:32

import utils.file_system
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватарка пользователя', null=True, upload_to=utils.file_system.user_avatar_upload_path),
        ),
    ]
