# Generated by Django 5.2.5 on 2025-10-10 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_populate_team_lifecycle_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Термин глоссария',
                'verbose_name_plural': 'Термины глоссария',
                'ordering': ['term'],
            },
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(fields=('term', 'team'), name='unique_term_per_team'),
        ),
    ]
