# Generated by Django 5.2.5 on 2025-10-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_migrate_to_project_based'),
        ('projects', '0004_update_translation_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glossaryterm',
            name='unique_term_per_project',
        ),
        migrations.AlterUniqueTogether(
            name='glossaryterm',
            unique_together={('term', 'project')},
        ),
    ]
