# Generated by Django 5.2.5 on 2025-10-10 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_text', 'Создание текста'), ('update_text', 'Обновление текста'), ('delete_text', 'Удаление текста'), ('autosave_text', 'Автосохранение текста'), ('create_project', 'Создание проекта'), ('update_project', 'Обновление проекта'), ('delete_project', 'Удаление проекта'), ('upload_image', 'Загрузка изображения'), ('delete_image', 'Удаление изображения'), ('view_project', 'Просмотр проекта'), ('access_denied', 'Отказ в доступе')], max_length=20, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог аудита контента',
                'verbose_name_plural': 'Логи аудита контента',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='content_con_user_id_b8b8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='content_con_action_a1a1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='content_con_object__c2c2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', '-updated_at'], name='content_pro_team_id_d3d3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='textcontent',
            index=models.Index(fields=['project', '-updated_at'], name='content_tex_project_e4e4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='textcontent',
            index=models.Index(fields=['author', '-updated_at'], name='content_tex_author__f5f5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecontent',
            index=models.Index(fields=['project', '-uploaded_at'], name='content_ima_project_g6g6g6_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecontent',
            index=models.Index(fields=['uploader', '-uploaded_at'], name='content_ima_uploade_h7h7h7_idx'),
        ),
    ]
