# Generated by Django 5.2.5 on 2025-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20251010_2053'),
    ]

    operations = [
        # Добавляем составные индексы для оптимизации часто используемых запросов
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_project_team_updated_idx ON content_project (team_id, updated_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_project_team_updated_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_textcontent_project_updated_idx ON content_textcontent (project_id, updated_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_textcontent_project_updated_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_textcontent_author_updated_idx ON content_textcontent (author_id, updated_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_textcontent_author_updated_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_textcontent_draft_updated_idx ON content_textcontent (is_draft, updated_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_textcontent_draft_updated_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_imagecontent_project_uploaded_idx ON content_imagecontent (project_id, uploaded_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_imagecontent_project_uploaded_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_imagecontent_uploader_uploaded_idx ON content_imagecontent (uploader_id, uploaded_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_imagecontent_uploader_uploaded_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_auditlog_user_timestamp_idx ON content_contentauditlog (user_id, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_auditlog_user_timestamp_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_auditlog_action_timestamp_idx ON content_contentauditlog (action, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS content_auditlog_action_timestamp_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS content_auditlog_object_idx ON content_contentauditlog (object_type, object_id);",
            reverse_sql="DROP INDEX IF EXISTS content_auditlog_object_idx;"
        ),
    ]
