# Generated by Django 5.2.5 on 2025-10-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_update_file_structure'),
        ('projects', '0004_update_translation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.RenameIndex(
            model_name='contentauditlog',
            new_name='content_con_user_id_d296bc_idx',
            old_name='content_con_user_id_b8b8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='contentauditlog',
            new_name='content_con_action_8f0ff4_idx',
            old_name='content_con_action_a1a1a1_idx',
        ),
        migrations.RenameIndex(
            model_name='contentauditlog',
            new_name='content_con_object__5bbc2c_idx',
            old_name='content_con_object__c2c2c2_idx',
        ),
        migrations.RenameIndex(
            model_name='imagecontent',
            new_name='content_ima_project_a85cb0_idx',
            old_name='content_ima_project_g6g6g6_idx',
        ),
        migrations.RenameIndex(
            model_name='imagecontent',
            new_name='content_ima_uploade_1a3109_idx',
            old_name='content_ima_uploade_h7h7h7_idx',
        ),
        migrations.RenameIndex(
            model_name='projectdocument',
            new_name='content_pro_project_a2210a_idx',
            old_name='content_projectdocument_project_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='projectdocument',
            new_name='content_pro_uploade_5b489d_idx',
            old_name='content_projectdocument_uploaded_by_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='projectdocument',
            new_name='content_pro_documen_59b066_idx',
            old_name='content_projectdocument_document_type_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='textcontent',
            new_name='content_tex_project_5fc3e3_idx',
            old_name='content_tex_project_e4e4e4_idx',
        ),
        migrations.RenameIndex(
            model_name='textcontent',
            new_name='content_tex_author__e029b7_idx',
            old_name='content_tex_author__f5f5f5_idx',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
