# Generated by Django 5.2.5 on 2025-10-10 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team_deactivated', 'Команда приостановлена'), ('team_reactivated', 'Команда возобновлена'), ('team_disbanded', 'Команда распущена'), ('team_invitation', 'Приглашение в команду'), ('task_assigned', 'Назначена задача'), ('project_update', 'Обновление проекта'), ('comment_mention', 'Упоминание в комментарии')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_team_status_changes', models.BooleanField(default=True, verbose_name='Email при изменении статуса команды')),
                ('email_team_invitations', models.BooleanField(default=True, verbose_name='Email при приглашениях в команды')),
                ('email_task_assignments', models.BooleanField(default=True, verbose_name='Email при назначении задач')),
                ('email_project_updates', models.BooleanField(default=False, verbose_name='Email при обновлениях проектов')),
                ('email_comment_mentions', models.BooleanField(default=True, verbose_name='Email при упоминаниях в комментариях')),
                ('web_team_status_changes', models.BooleanField(default=True, verbose_name='Веб уведомления об изменении статуса команды')),
                ('web_team_invitations', models.BooleanField(default=True, verbose_name='Веб уведомления о приглашениях в команды')),
                ('web_task_assignments', models.BooleanField(default=True, verbose_name='Веб уведомления о назначении задач')),
                ('web_project_updates', models.BooleanField(default=True, verbose_name='Веб уведомления об обновлениях проектов')),
                ('web_comment_mentions', models.BooleanField(default=True, verbose_name='Веб уведомления об упоминаниях в комментариях')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notification_recipie_b8b8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notification_recipie_e8e8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notification_notific_a1a1a1_idx'),
        ),
    ]
