# Generated by Django 5.2.5 on 2025-10-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_a972ce_idx',
            old_name='notification_recipie_b8b8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notification_recipie_e8e8e8_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_f2898f_idx',
            old_name='notification_notific_a1a1a1_idx',
        ),
    ]
